// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcBQjpHHx78Rry01Owy5zORBP_7jXNvs0',
    appId: '1:328195120179:web:4c1feee25ffe61999b9746',
    messagingSenderId: '328195120179',
    projectId: 'wadul-guse',
    authDomain: 'wadul-guse.firebaseapp.com',
    storageBucket: 'wadul-guse.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWheqeI7gyN9OxGBSVDPXZwDVuq1REakE',
    appId: '1:328195120179:android:f206ff70d48fa9539b9746',
    messagingSenderId: '328195120179',
    projectId: 'wadul-guse',
    storageBucket: 'wadul-guse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ2Wsjp5qqKRBFqIMA3TlyvdGguLiQsPQ',
    appId: '1:328195120179:ios:d26619c22f58bd9c9b9746',
    messagingSenderId: '328195120179',
    projectId: 'wadul-guse',
    storageBucket: 'wadul-guse.firebasestorage.app',
    iosBundleId: 'com.example.projectPbm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ2Wsjp5qqKRBFqIMA3TlyvdGguLiQsPQ',
    appId: '1:328195120179:ios:d26619c22f58bd9c9b9746',
    messagingSenderId: '328195120179',
    projectId: 'wadul-guse',
    storageBucket: 'wadul-guse.firebasestorage.app',
    iosBundleId: 'com.example.projectPbm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcBQjpHHx78Rry01Owy5zORBP_7jXNvs0',
    appId: '1:328195120179:web:d6ae6f2d74a9790b9b9746',
    messagingSenderId: '328195120179',
    projectId: 'wadul-guse',
    authDomain: 'wadul-guse.firebaseapp.com',
    storageBucket: 'wadul-guse.firebasestorage.app',
  );
}
